version: "3.5"
volumes:
  fernet_keys:
  db_data:
  bootstraped1:
  bootstraped2:

networks:
  openstack:
    external:
      name: os_idp_keystone

services:
  database:
    image: mysql:5.7
    container_name: database
    networks:
      openstack:
        ipv4_address: 192.168.200.3
    volumes:
    - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: r00tme


  keystone:
    volumes:
      - fernet_keys:/fernet_keys
      - bootstraped1:/bootstraped
    ports:
      - "5000:5000"
    build:
      context: ./keystone
      args:
        keystone_version: stable/stein
    environment:
      - BOOTSTRAP=1
      - DB_NAME=database
      - KEYSTONE_PORT=5000
      - HOST_NAME=keystone
      - REGION=RegionOne
    container_name: keystone
    hostname: keystone
    command: ["/wait-for-it.sh", "-s", "-t", "60", "database:3306", "--", "bash", "/home/keystone/bootstrap/run.sh"]
    networks:
      openstack:
        ipv4_address: 192.168.200.6
    depends_on:
      - database

  keystone2:
    volumes:
      - fernet_keys:/fernet_keys
      - bootstraped2:/bootstraped
    ports:
      - "5001:5001"
    build:
      context: ./keystone
      args:
        keystone_version: stable/stein
    environment:
    - BOOTSTRAP=1
    - DB_NAME=database
    - KEYSTONE_PORT=5001
    - HOST_NAME=keystone2
    - REGION=RegionTWO
    container_name: keystone2
    hostname: keystone2
    command: ["./wait-for-it.sh", "-s", "-t", "60", "database:3306", "--", "bash", "/home/keystone/bootstrap/run.sh"]
    networks:
      openstack:
       ipv4_address: 192.168.200.7
    depends_on:
      - database
      - keystone
