version: "3.5"
volumes:
  bootstrap.ldif:

networks:
  openstack:
     driver: bridge
     name: os_idp_keystone
     ipam:
       driver: default
       config:
          - subnet: 192.168.200.0/24

services:
  idp:
    build: ./shibboleth
    container_name: idp
    hostname: idp
    entrypoint: java -Didp.home=/opt/shibboleth-idp -Djetty.base=/opt/shibboleth-idp/jetty-base -Djetty.logs=/opt/shibboleth-idp/jetty-base/logs -jar /dists/jetty/start.jar
    # entrypoint: tail -f /var/log/bootstrap.log
    # network_mode: host
    networks:
      openstack:
        ipv4_address: 192.168.200.4
    extra_hosts:
      - "ldap:192.168.200.2"
    ports:
      - "443:8443"
    depends_on:
      - ldap

  ldap:
     image: osixia/openldap:1.2.3
     container_name: ldap
     hostname: ldap
     command: [--copy-service]
     volumes:
       - ./domain.ldif:/container/service/slapd/assets/config/bootstrap/ldif/data.ldif
     networks:
       openstack:
         ipv4_address: 192.168.200.2
     environment:
       LDAP_ORGANISATION: Openstack
       LDAP_DOMAIN: openstack.com
       LDAP_ADMIN_PASSWORD: r00tme

  phpldapadmin:
     image: osixia/phpldapadmin
     hostname: phpldapadmin
     container_name: phpldapadmin
     networks:
       openstack:
         ipv4_address: 192.168.200.5
     environment:
       PHPLDAPADMIN_LDAP_HOSTS: ldap
       PHPLDAPADMIN_HTTPS: "false"

